let state=null,map=null,chart=null,lastRefresh=Date.now();
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const levelClass=l=>String(l).toLowerCase();
async function get(url){const r=await fetch(url); if(!r.ok) throw Error(await r.text()); return r.json()}
async function refresh(){try{state=await get('/api/state'); lastRefresh=Date.now(); render()}catch(e){console.error(e)}}
function render(){
 $('lastUpdate').textContent='Updated '+state.local_time; $('refreshAge').textContent='just now';
 $('mCritical').textContent=state.metrics.critical; $('mRisk').textContent=Math.max(...state.zones.map(z=>z.prediction.probability))+'%'; $('mSos').textContent=state.metrics.open_sos; $('mShip').textContent=state.metrics.shipments;
 $('feed').innerHTML=state.feed.map(x=>`<div class="feedItem"><time>${esc(x.time)}</time>${esc(x.text)}</div>`).join('');
 $('priority').innerHTML=zoneRows(state.zones.slice(0,6),true);
 const top=state.zones[0]; $('heroZone').textContent=top.name+' · Flood'; $('heroProb').textContent=top.prediction.probability+'%'; $('heroText').textContent=`24-hour model probability · vulnerability ${top.vulnerability.toFixed(2)} · severity ${top.level}`;
 $('warningsTable').innerHTML=`<div class="tr head"><div>ZONE</div><div>HAZARD</div><div>PROBABILITY</div><div>HORIZON</div></div>`+state.zones.map(z=>`<div class="tr"><strong>${esc(z.name)}</strong><div>Flood</div><div>${z.prediction.probability}%</div><div><span class="pill ${levelClass(z.level)}">${z.level}</span></div></div>`).join('');
 $('vulnTable').innerHTML=`<div class="tr head"><div>ZONE</div><div>SEVERITY</div><div>VULNERABILITY</div><div>OPEN SOS</div></div>`+state.zones.map(z=>`<div class="tr"><strong>${esc(z.name)}</strong><div><span class="pill ${levelClass(z.level)}">${z.level} · ${z.score}</span></div><div>${z.vulnerability.toFixed(2)}</div><div>${z.open_sos}</div></div>`).join('');
 renderMap(); renderChart(); renderField(); renderLedger();
}
function zoneRows(zs){return `<div class="tr head"><div>ZONE</div><div>RISK</div><div>VULN.</div><div>LEVEL</div></div>`+zs.map(z=>`<div class="tr"><strong>${esc(z.name)}</strong><div>${z.prediction.probability}%</div><div>${z.vulnerability.toFixed(2)}</div><div><span class="pill ${levelClass(z.level)}">${z.level}</span></div></div>`).join('')}
function renderMap(){if(!map){map=L.map('map',{zoomControl:false}).setView([34.065,74.82],12);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map)}
 map.eachLayer(l=>{if(l instanceof L.Circle||l instanceof L.Marker) map.removeLayer(l)});
 state.zones.forEach(z=>{const c={CRITICAL:'#ff5d66',HIGH:'#18ddf2',MODERATE:'#35f3a4',LOW:'#66d39e'}[z.level]||'#53d7df'; L.circle([z.lat,z.lon],{radius:350+z.prediction.probability*7,color:c,fillColor:c,fillOpacity:.16,weight:2}).addTo(map).bindPopup(`<b>${esc(z.name)}</b><br>Flood probability: ${z.prediction.probability}%<br>Vulnerability: ${z.vulnerability}<br>Severity: ${z.level}`); L.circleMarker([z.lat,z.lon],{radius:5,color:c,fillColor:c,fillOpacity:1,weight:2}).addTo(map)});
 const hubs=[[34.051,74.812,'Lal Chowk Relief Hub'],[34.020,74.870,'Pantha Chowk Depot'],[34.045,74.752,'Bemina Logistics Hub'],[34.062,74.850,'Soura Emergency Store']]; hubs.forEach(h=>L.marker([h[0],h[1]],{icon:L.divIcon({className:'hubIcon',html:'◆',iconSize:[20,20]})}).addTo(map).bindPopup('<b>RELIEF HUB</b><br>'+h[2]));
}
function renderChart(){const ctx=$('riskChart'); if(chart) chart.destroy(); const labels=['Now','+4h','+8h','+12h','+16h','+20h','+24h']; const p=Math.max(...state.zones.map(z=>z.prediction.probability)); const vals=labels.map((_,i)=>Math.max(4,Math.min(99,p-(6-i*.3)+i*1.2))); chart=new Chart(ctx,{type:'line',data:{labels,datasets:[{data:vals,borderWidth:2,tension:.35,pointRadius:2}]},options:{plugins:{legend:{display:false}},scales:{x:{grid:{color:'#162834'},ticks:{color:'#6e8492',font:{size:9}}},y:{min:0,max:100,grid:{color:'#162834'},ticks:{color:'#6e8492',font:{size:9},callback:v=>v+'%'}}}}})}
async function renderResources(){const d=await get('/api/resources');$('stockTable').innerHTML='<div class="stock">'+['HUB','FOOD','MEDICAL','WATER','TARPS','OXYGEN'].map(x=>`<div class="head">${x}</div>`).join('')+d.hubs.map(h=>[h.name,h.food,h.medical,h.water,h.tarps,h.oxygen].map(x=>`<div>${esc(x)}</div>`).join('')).join('')+'</div>';$('recs').innerHTML=d.recommendations.map(r=>`<div class="rec"><div class="recTop"><b>${esc(r.item)} · ${r.qty}</b><span class="pill ${levelClass(r.priority)}">${r.priority}</span></div><p>${esc(r.from)} → ${esc(r.to)} · ${r.distance_km} km · ${esc(r.reason)}</p></div>`).join('')}
function renderField(){$('fieldTable').innerHTML='<div class="tr head"><div>ZONE</div><div>NEED</div><div>PEOPLE</div><div>STATUS</div></div>'+[['Rainawari','Water',180,'OPEN'],['Downtown Srinagar','Medical',62,'IN TRANSIT'],['Soura','Shelter',94,'OPEN'],['Bemina','Rescue',48,'OPEN'],['Pantha Chowk','Food',130,'RESOLVED']].map(r=>`<div class="tr"><strong>${r[0]}</strong><div>${r[1]}</div><div>${r[2]}</div><div><span class="pill ${r[3]=='OPEN'?'critical':'low'}">${r[3]}</span></div></div>`).join('')}
function renderLedger(){const l=state.ledger||[];$('ledger').innerHTML='<div class="tr head"><div>STEP</div><div>EVENT</div><div>PREVIOUS</div><div>FINGERPRINT</div></div>'+l.map(x=>`<div class="tr"><strong>#${x.step}</strong><div>${esc(x.payload?.event||'movement')}</div><div>${String(x.previous).slice(0,10)}…</div><div>${x.fingerprint.slice(0,12)}…</div></div>`).join('')||'<div class="feedItem">No local ledger events yet. Add a demo movement to create a chain.</div>'}
async function demoLedger(){await fetch('/api/ledger',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event:'shipment movement',shipment:'SHP-DEMO-01',item:'Water packs',qty:120,from:'Pantha Chowk Depot',to:'Rainawari'})});refresh()}
function nav(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(b.dataset.view).classList.add('active');$('pageTitle').textContent=b.querySelector('span').textContent;if(b.dataset.view==='resources')renderResources()})}
['rain','river','soil'].forEach(x=>{$(x+'Input').oninput=e=>{$(x+'Out').textContent=e.target.value+(x==='rain'?' mm':'%')}});
$('simulate').onclick=async()=>{const body={rain_1h:12,rain_6h:42,rain_24h:88,rain_72h:145,forecast_rain_24h:+$('rainInput').value,river_discharge_pct:+$('riverInput').value,river_rise_6h_pct:14,soil_moisture_pct:+$('soilInput').value,elevation_m:1585,slope_pct:4,river_distance_km:2.2,drainage_density:2.5,population_density:7000,vulnerable_population_pct:22};const d=await fetch('/api/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(r=>r.json());$('baseP').textContent=d.baseline.probability+'%';$('stressP').textContent=d.stressed.probability+'%';$('deltaText').textContent=`Scenario changes predicted probability by ${d.delta>=0?'+':''}${d.delta} percentage points.`};
$('refreshBtn').onclick=refresh;nav();refresh();setInterval(refresh,30000);setInterval(()=>{const s=Math.round((Date.now()-lastRefresh)/1000);$('refreshAge').textContent=s<2?'just now':s+'s ago'},1000);
